### ISSUE TITLE
Cancel timeout properly

### ISSUE THREAD

**Issue by Yuras** [snapframework/snap-server#104]
Cancel was added (see https://github.com/snapframework/snap-server/issues/99#issuecomment-301608097) in this commit: https://github.com/snapframework/snap-server/commit/3d03b32a6f2d6ecdf9698df09f4ef61096ca5054

But here: https://github.com/snapframework/snap-server/commit/3d03b32a6f2d6ecdf9698df09f4ef61096ca5054#diff-6b4d869d46e926e6a8a592022cf1aa89R198 `cancel` is returned, not called. As a result, threads are retained forever.

ping @gregorycollins

**Comment by gregorycollins** [comment]
Sigh. Good catch
