### ISSUE TITLE
Compatibility with random-1.2

### ISSUE THREAD

**Issue by sjakobi** [snapframework/snap-server#134]
The testsuite uses has a dependency on `random` that needs to be bumped.

So far I haven't been able to build it with the new version yet though, due to

* [ ] https://github.com/haskell/test-framework/pull/53

…and more importantly

* [ ] https://github.com/snapframework/snap-core/pull/295

Context: https://github.com/commercialhaskell/stackage/issues/5474

**Comment by lehins** [comment]
Both of the mentioned PRs have been merged and #135 has been merged too. Only missing test-framework and test-framework-quickcheck2 releases now, right?

**Comment by sjakobi** [comment]
@lehins Indeed, if I use `allow-newer` for these two dependencies, the testsuite builds fine and passes.

Nothing left to do on this side! :)
