### ISSUE TITLE
Support for GHC 9.0.1

### ISSUE THREAD

**Issue by sjakobi** [snapframework/snap-server#141]
The latest release requires base < 4.15, so at least that bound needs to be relaxed.

**Comment by nrnrnr** [comment]
What are the chances of getting this change into an updated version on Hackage?

**Comment by andreasabel** [comment]
This issue looks fixed: https://hackage.haskell.org/package/snap-server-1.1.2.0/revisions/

**Comment by sjakobi** [comment]
Great news! :) Thank you, @mightybyte!
