### ISSUE TITLE
Compatibility with transformers 0.6 and mtl 2.3

### ISSUE THREAD

**Issue by sjakobi** [snapframework/snap-server#144]
https://hackage.haskell.org/package/transformers-0.6.0.0/changelog

Could you upload a compatible release or make a Hackage revision?

**Comment by sjakobi** [comment]
Compatibility with mtl-2.3 would also be great to have!

**Comment by ysangkok** [comment]
This depends on https://github.com/snapframework/snap-core/issues/313 , I think
