### ISSUE TITLE
getaddrinfo issue on BSD/Dragonfly

### ISSUE THREAD

**Issue by gisenmann** [snapframework/snap-server#56]
Hi!
I need this small change to the getaddrinfo call in Snap/Internal/Http/Server/Address.hs
-    let hints = defaultHints { addrFlags = [AI_NUMERICSERV] }
+    let hints = defaultHints { addrFlags = [AI_NUMERICSERV]
+                             , addrSocketType = Stream
+                             }
on Dragonfly. Without I get "getAddrInfo: does not exist (servname not supported for ai_socktype)".

**Comment by cgag** [comment]
This was fixed in #67, it can be closed.
