### ISSUE TITLE
Sometimes sockets are not closed.

### ISSUE THREAD

**Issue by dikmax** [snapframework/snap-server#63]
I found out that server stops accepting connections because there were too many opened sockets in CLOSE_WAIT state. For my server it happens every one or two days and only for ssl connections.

**Comment by pbv** [comment]
Any update on this? I am experiencing a similar behavior using snap-server-1.0.1.1 serving SSL connections. The server stops responding and netstat reports ~80 connections in CLOSE_WAIT state.
For my server this happens infrequently - maybe once every two weeks.

**Comment by gregorycollins** [comment]
@pbv I would love a reproduction testcase. I just fixed an issue with the timeout manager in 3d03b32a6f2d6ecdf9698df09f4ef61096ca5054 -- that's released as 1.0.2.2, please let me know if that version helps.

**Comment by pbv** [comment]
@gregorycollins OK, I've updated to 1.0.2.2 I check if the problem occurs again.

 Unfortunately I haven't been able to reliably reproduce the bug. It appears to be unrelated to server load (i.e. some of the hangups during the night there shouldn't much load - this is a web app for students' exercises).  What I can confirm is that I've set up a separate server running snap-server-0.9.5.1 and that one does *not* exhibit this problem.

**Comment by pbv** [comment]
@gregorycollins: I confirm that the snap-server-1.0.2.2 still stops accepting connections with lots of connections in CLOSE_WAIT state. Is there anything you suggest I do to try to diagnose the problem?

**Comment by gregorycollins** [comment]
@pbv: ok, some thoughts for debugging this:

Add debug calls inside snap-server for the .TLS and .Socket modules. I am especially interested in tracing the call to "sClose" and reporting exceptions caught by any exception handlers. I'm going to have a look to audit our exception handlers.

**Comment by gregorycollins** [comment]
@pbv: can you try e86f8a825305c7b4b344e162d7b49c2119922a56 ? That seems like the only obvious point where we might be leaking the socket.

**Comment by pbv** [comment]
@gregorycollins:OK I'll try that patch (BTW, the .TLS module is missing an import for onException).

**Comment by gregorycollins** [comment]
@pbv fixed in 59989aef78f82b846a768f6f436f4e9fa8bea92b

**Comment by cgibbard** [comment]
Is there a reason this is still open?
