### ISSUE TITLE
Switch to better option parsing library

### ISSUE THREAD

**Issue by sopvop** [snapframework/snap-server#70]
Using System.Console.GetOpt is problematic.
Error reporting from it is real pain.
I think snap should switch to one of the applicative/monadic option parsers instead.

One of the bad things in snap-server config is --proxy options, which uses `error` to report errors, and since that value is actually evaluated in other place, server just dies without error message because at that space it eats all exceptions. (Also, eating all exceptions is bad)

Of course it's a breaking change for people who added custom options, but I'm sure everyone will be glad to get rid of GetOpt :)

**Comment by rgrinberg** [comment]
+1 for optparse-applicative

**Comment by sopvop** [comment]
Args parsing is not that important to add deps to package. Can be done externally.
