### ISSUE TITLE
Allow binding to unix socket

### ISSUE THREAD

**Issue by wereHamster** [snapframework/snap-server#76]
I tried to use `setBind "/path/to/unix.socket"` but the server parses the bytestring as IP address.

**Comment by sopvop** [comment]
Implemented in 1.0. Config has setUnixSocket and setUnixSocketAccessMode setters.

**Comment by wereHamster** [comment]
What happens when I do both `setBind` and `setUnixSocket` ?

**Comment by sopvop** [comment]
Server will listen on both

**Comment by wereHamster** [comment]
Is there an ETA when 1.0 will be released?

**Comment by gregorycollins** [comment]
We are close to code complete (you could start demoing it by running from git master now) but have quite a few tasks to do still before 1.0 will be ready.
