### ISSUE TITLE
Test suite build failure

### ISSUE THREAD

**Issue by snoyberg** [snapframework/snap-server#89]
```
[26 of 26] Compiling Main             ( test/TestSuite.hs, dist/build/testsuite/testsuite-tmp/Main.o )

test/TestSuite.hs:16:1: error:
    Failed to load interface for ‘Snap.Internal.Http.Server.Address.Tests’
    Perhaps you meant
      Snap.Internal.Http.Server.Address
      Snap.Internal.Http.Server.Parser
      Snap.Internal.Http.Server.Session
    Use -v to see a list of the files searched for.
```

**Comment by mightybyte** [comment]
Can't reproduce

**Comment by Yuras** [comment]
The `Snap.Internal.Http.Server.Address.Tests` module is not mentioned in the cabal file, it seems to be the cause.

Note that `Snap.Internal.Http.Server.Address` module it mentioned twice: [1](https://github.com/snapframework/snap-server/blob/master/snap-server.cabal#L170), [2](https://github.com/snapframework/snap-server/blob/master/snap-server.cabal#L184). The latter one is probably a typo.

**Comment by mightybyte** [comment]
Ahh yes, it looks like that fixed it.
