### ISSUE TITLE
FreeBSD failure to install

### ISSUE THREAD

**Issue by GrappigPanda** [snapframework/snap-server#91]
Hey there.

Whenever attempting `stack install snap`, I've found that the build process fails due to snap-server.

I get the following error:
```
Progress: 72/76
--  While building package snap-server-1.0.1.0 using:
      /usr/home/ian/.stack/setup-exe-cache/x86_64-freebsd/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-freebsd/Cabal-1.24.0.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /usr/home/ian/Development/waitingfortodo/Backend/.stack-work/logs/snap-server-1.0.1.0.log

    Configuring snap-server-1.0.1.0...
    Building snap-server-1.0.1.0...
    Preprocessing library snap-server-1.0.1.0...
    [ 1 of 20] Compiling System.SendFile.FreeBSD ( .stack-work/dist/x86_64-freebsd/Cabal-1.24.0.0/build/System/SendFile/FreeBSD.hs, .stack-work/dist/x86_64-freebsd/Cabal-1.24.0.0/build/System/SendFile/FreeBSD.o )
    
    /tmp/stack24898/snap-server-1.0.1.0/src/System/SendFile/FreeBSD.hsc:33:1: error:
        The type signature for ‘sendFile’ lacks an accompanying binding
```

Whenever I look at the accompanying file (https://github.com/snapframework/snap-server/blob/master/src/System/SendFile/FreeBSD.hsc), I notice it's just a type signature.

I'm mostly wondering if this is due to historical reasons that it's not implemented, or if it's due to BSD reasons--a.k.a, nobody uses it :)

Regardless, I'm willing to contribute, but I didn't want to charge straight into it in the case that there is a historical reason for it not being implemented.

**Comment by mightybyte** [comment]
I really don't know what the reason is for that.  I presume it's simply an oversight because nobody ever tried building on FreeBSD.  If you are building on FreeBSD and can provide a fix, that would be greatly appreciated.!

**Comment by cmoore** [comment]
On the off chance that you want to just get things working, setting the 'portable' flag will skip building with sendfile.

It's not the best, but if you serve static content with nginx anyway, it's not too bad.
